name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      name: Install pnpm
      with:
        version: 9
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: "pnpm"

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install
